Gspstore/src/com/jeecg/action/BaseAction.java
package com.jeecg.action;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts2.ServletActionContext;
import org.apache.struts2.convention.annotation.Namespace;
import org.apache.struts2.convention.annotation.ParentPackage;
import org.springframework.beans.factory.annotation.Autowired;

import com.alibaba.fastjson.JSON;
import com.jeecg.pageModel.SessionInfo;
import com.jeecg.util.ExceptionUtil;
import com.jeecg.util.ResourceUtil;
import com.opensymphony.xwork2.ActionSupport;

import cn.neu.service.NoticeServiceI;

/**
 * 基础ACTION,其他ACTION继承此ACTION来获得writeJson和ActionSupport的功能
 * 
 * @author zhangdaihao
 * 
 */
@ParentPackage("defaultPackage")
@Namespace("/")
public class BaseAction extends ActionSupport {

	private static final long serialVersionUID = 1L;

	private static final Logger logger = Logger.getLogger(BaseAction.class);
	
	// 仅在NoticeServer中使用
	public static NoticeServiceI noticeService;
	
	public NoticeServiceI getNoticeService() {
		return noticeService;
	}

	@Autowired
	public void setNoticeService(NoticeServiceI noticeService) {
		BaseAction.noticeService = noticeService;
	}

	public HttpSession getSession() {
		return getRequest().getSession();
	}

	public HttpServletRequest getRequest() {
		return ServletActionContext.getRequest();
	}

	public HttpServletResponse getResponse() {
		return ServletActionContext.getResponse();
	}
	
	public SessionInfo getSessionInfo(){
		SessionInfo sessionInfo = (SessionInfo) ServletActionContext.getRequest().getSession().getAttribute(ResourceUtil.getSessionInfoName());
		return sessionInfo;
	}

	/**
	 * 将对象转换成JSON字符串，并响应回前台
	 * 
	 * @param object
	 * @throws IOException
	 */
	public void writeJson(Object object) {
		try {
			// SerializeConfig serializeConfig = new SerializeConfig();
			// serializeConfig.setAsmEnable(false);
			// String json = JSON.toJSONString(object);
			// String json = JSON.toJSONString(object, serializeConfig, SerializerFeature.PrettyFormat);
			String json = JSON.toJSONStringWithDateFormat(object, "yyyy-MM-dd HH:mm:ss");
			// String json = JSON.toJSONStringWithDateFormat(object, "yyyy-MM-dd HH:mm:ss", SerializerFeature.PrettyFormat);
			ServletActionContext.getResponse().setContentType("text/html;charset=utf-8");
			ServletActionContext.getResponse().getWriter().write(json);
			ServletActionContext.getResponse().getWriter().flush();
		} catch (IOException e) {
			logger.debug(ExceptionUtil.getExceptionMessage(e));
		}
	}
}

Gspstore/WebRoot/layout/center.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<script type="text/javascript" charset="utf-8">
	var centerTabs;
	var tabsMenu;
	$(function() {
		tabsMenu = $('#tabsMenu').menu({
			onClick : function(item) {
				var curTabTitle = $(this).data('tabTitle');
				var type = $(item.target).attr('type');

				if (type === 'refresh') {
					refreshTab(curTabTitle);
					return;
				}

				if (type === 'close') {
					var t = centerTabs.tabs('getTab', curTabTitle);
					if (t.panel('options').closable) {
						centerTabs.tabs('close', curTabTitle);
					}
					return;
				}

				var allTabs = centerTabs.tabs('tabs');
				var closeTabsTitle = [];

				$.each(allTabs, function() {
					var opt = $(this).panel('options');
					if (opt.closable && opt.title != curTabTitle && type === 'closeOther') {
						closeTabsTitle.push(opt.title);
					} else if (opt.closable && type === 'closeAll') {
						closeTabsTitle.push(opt.title);
					}
				});

				for ( var i = 0; i < closeTabsTitle.length; i++) {
					centerTabs.tabs('close', closeTabsTitle[i]);
				}
			}
		});

		centerTabs = $('#centerTabs').tabs({
			fit : true,
			border : false,
			onContextMenu : function(e, title) {
				e.preventDefault();
				tabsMenu.menu('show', {
					left : e.pageX,
					top : e.pageY
				}).data('tabTitle', title);
			}
		});
	});
	
	function refreshTab(title) {
		var tab = centerTabs.tabs('getTab', title);
		centerTabs.tabs('update', {
			tab : tab,
			options : tab.panel('options')
		});
	}
	function addTab(node) {
		if (centerTabs.tabs('exists', node.text)) {
			//refreshTab(node.text); //增加左侧菜单点击刷新功能 libc 2012-9-24
			centerTabs.tabs('select', node.text);
			
		} else {
			if (node.attributes.url && node.attributes.url.length > 0) {
				//if (node.attributes.url.indexOf('!druid.action') == -1) {/*数据源监控页面不需要开启等待提示*/
					$.messager.progress({
						text : '正在加载...',
						interval : 100
					});
					window.setTimeout(function() {
						try {
							$.messager.progress('close');
						} catch (e) {
						}
					}, 0);
				//	}
				centerTabs.tabs('add', {
					title : node.text,
					closable : true,
					iconCls : node.iconCls,
					content : '<iframe src="' + node.attributes.url + '" frameborder="0" style="border:0;width:100%;height:99.4%;"></iframe>',
					tools : [ {
						iconCls : 'icon-mini-refresh',
						handler : function() {
							refreshTab(node.text);
						}
					} ]
				});
			} else {
				centerTabs.tabs('add', {
					title : node.text,
					closable : true,
					iconCls : node.iconCls,
					content : '<iframe src="error/err.jsp" frameborder="0" style="border:0;width:100%;height:99.4%;"></iframe>',
					tools : [ {
						iconCls : 'icon-mini-refresh',
						handler : function() {
							refreshTab(node.text);
						}
					} ]
				});
			}
		}
	}
	
	
	//--功能描述：左侧菜单添加tab（手风琴样式）
	function addTabs(text,url,ciconCls) {
		if (centerTabs.tabs('exists', text)) {
			//refreshTab(text); //增加左侧菜单点击刷新功能 libc 2012-9-24
			centerTabs.tabs('select', text);
		} else {
			if (url && url.length > 0) {
				//if (node.attributes.url.indexOf('!druid.action') == -1) {/*数据源监控页面不需要开启等待提示*/
					$.messager.progress({
						text : '正在加载...',
						interval : 100
					});
					window.setTimeout(function() {
						try {
							$.messager.progress('close');
						} catch (e) {
						}
					}, 0);
				//	}
				centerTabs.tabs('add', {
					title : text,
					closable : true,
					iconCls : ciconCls,
					content : '<iframe src="' + url + '" frameborder="0" style="border:0;width:100%;height:99.4%;"></iframe>',
					tools : [ {
						iconCls : 'icon-mini-refresh',
						handler : function() {
							refreshTab(text);
						}
					} ]
				});
			} else {
				centerTabs.tabs('add', {
					title : text,
					closable : true,
					iconCls : iconCls,
					content : '<iframe src="error/err.jsp" frameborder="0" style="border:0;width:100%;height:99.4%;"></iframe>',
					tools : [ {
						iconCls : 'icon-mini-refresh',
						handler : function() {
							refreshTab(text);
						}
					} ]
				});
			}
		}
	}
</script>
<div id="centerTabs">
	<!-- href="layout/portal.jsp" -->
  <div title="公告版" border="false" style="overflow: hidden;"></div>
</div>
<div id="tabsMenu" style="width: 120px;display:none;">
	<div type="refresh">刷新</div>
	<div class="menu-sep"></div>
	<div type="close">关闭</div>
	<div type="closeOther">关闭其他</div>
	<div type="closeAll">关闭所有</div>
</div>

Gspstore/WebRoot/layout/north.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<script type="text/javascript" charset="utf-8">
	function logout(b) {
		$.post('userAction!logout.action', function() {
			if (b) {
				if (sy.isLessThanIe8()) {
					//loginAndRegDialog.dialog('open');
					window.location.href="login.jsp";
				} else {
					location.replace(sy.bp());
				}
			} else {
				//loginAndRegDialog.dialog('open');
				window.location.href="login.jsp";
			}
		});
	}

	var userInfoWindow;
	function showUserInfo() {
		userInfoWindow = $('<div/>').window({
			modal : true,
			title : '当前用户信息',
			width : 350,
			height : 300,
			collapsible : false,
			minimizable : false,
			maximizable : false,
			href : 'userAction!showUserInfo.action',
			onClose : function() {
				$(this).window('destroy');
			}
		});
	}
	
	var iframeDialog;
	var showCdescDialog;
	$(function() {
		iframeDialog = $('#iframeDialog').show().dialog({
			title : 'POP弹出页面',
			modal : true,
			closed : true,
			maximizable : false,
			onClose : function(){
			    document.getElementById("iframe").src = "about:blank";
			    location.reload();
			}
		});
		showCdescDialog = $('#showCdescDialog').show().dialog({
			title : '内容',
			modal : true,
			closed : true,
			maximizable : true,
		});
		$('#informMenu').menubutton({
	        iconCls: 'icon-tip',
	        menu: '#layout_north_informMenu',
	        text: "0条通知"
	    });
		//添加分隔线
		$('#layout_north_informMenu').menu('appendItem', {
			id:"informSeparator",
			separator: true
		});
		$('#layout_north_informMenu').menu('appendItem', {
			text: '查看全部通知',
			id:"informAll",
			onclick: function(){showInform();}
		});
		$('#noticeMenu').menubutton({
	        iconCls: 'icon-tip',
	        menu: '#layout_north_noticeMenu',
	        text: "0条公告/公文"
	    });
		//添加分隔线
		$('#layout_north_noticeMenu').menu('appendItem', {
			id:"noticeSeparator",
			separator: true
		});
		$('#layout_north_noticeMenu').menu('appendItem', {
			text: '查看全部公告/公文',
			id:"noticeAll",
			onclick: function(){showNotice();}
		});
		initWebSocket();
	});
	
	
	function initWebSocket(){
		var socket;
		if(!window.WebSocket){
			console.info("尝试使用MozWebSocket");
			window.WebSocket = window.MozWebSocket;
		}
		var wsUri = "ws:localhost:8080/Gspstore/noticeServer?userId=${sessionScope.sessionInfo.userId }";
		socket = new WebSocket(wsUri);
		socket.onmessage = function(event){
			console.info("receive a menu"+event.data);
			addMenuItem(event.data);
		};
		socket.onopen = function(event){
			//alert("websocket open success")
			console.info("websocket open success"+event);
		};
		socket.onerror = function(event){
			$.messager.alert('提示','可能浏览器不支持WebSocket,请更换浏览器后重试，否则通知功能将无法使用！','error');
			console.info(event);
			socket.close();
		};
	}
	
	function addMenuItem(data){
		//根据websocket返回的结果 修改菜单栏
		data = eval("(" + data + ")");//字符串转成json
			if(data.isAnnouncement==0){
				// 移除分隔行和最后一行
				$('#layout_north_informMenu').menu('removeItem', $('#informSeparator')[0]);
				$('#layout_north_informMenu').menu('removeItem', $('#informAll')[0]);
				//添加通知
				if(new Date(data.expiryTime.replace(/-/g,"/"))-new Date()<86400000){
					//24小时后失效
					$('#layout_north_informMenu').menu('appendItem', {
						text: "<font color='red'><strong>"+data.title+"</strong></font>",
						iconCls: "icon-cancel",
						id:data.noticeId,
						onclick: function(){
							showCdesc("inform",this);
						}
					});
				}else{
					$('#layout_north_informMenu').menu('appendItem', {
						text: "<strong>"+data.title+"</strong>",
						id:data.noticeId,
						onclick: function(){
							showCdesc("inform",this);
						}
					});
				}
				//添加分隔线
				$('#layout_north_informMenu').menu('appendItem', {
					id:"informSeparator",
					separator: true
				});
				$('#layout_north_informMenu').menu('appendItem', {
					text: '查看全部通知',
					id:"informAll",
					onclick: function(){showInform();}
				});
				var text = $('#informMenu')[0].text;
				text = (Number(text.split("条")[0])+1)+"条通知";
				$('#informMenu').menubutton({
			        iconCls: 'icon-tip',
			        menu: '#layout_north_informMenu',
			        text: text
			    });
			}else{
				// 移除分隔行和最后一行
				$('#layout_north_noticeMenu').menu('removeItem', $('#noticeSeparator')[0]);
				$('#layout_north_noticeMenu').menu('removeItem', $('#noticeAll')[0]);
				//添加公告/公文
				if(new Date(data.expiryTime.replace(/-/g,"/"))-new Date()<86400000){
					//24小时后失效
					$('#layout_north_noticeMenu').menu('appendItem', {
						text: "<font color='red'><strong>"+data.title+"</strong></font>",
						iconCls: "icon-cancel",
						id:data.noticeId,
						onclick: function(){
							showCdesc("notice",this);
						}
					});
				}else{
					$('#layout_north_noticeMenu').menu('appendItem', {
						text: "<strong>"+data.title+"</strong>",
						id:data.noticeId,
						onclick: function(){
							showCdesc("notice",this);
						}
					});
				}
				//添加分隔线
				$('#layout_north_noticeMenu').menu('appendItem', {
					id:"noticeSeparator",
					separator: true
				});
				$('#layout_north_noticeMenu').menu('appendItem', {
					text: '查看全部公告/公文',
					id:"noticeAll",
					onclick: function(){showNotice();}
				});
				var text = $('#noticeMenu')[0].text;
				text = (Number(text.split("条")[0])+1)+"条公告/公文";
				$('#noticeMenu').menubutton({
			        iconCls: 'icon-tip',
			        menu: '#layout_north_noticeMenu',
			        text: text
			    });
			}
	}
	
	function showInform(){
		$('#iframeDialog').dialog('setTitle', '我的通知'); 
		iframeDialog.dialog('open');
		$("#loading").css("display","block");
		document.getElementById("iframe").src = "${pageContext.request.contextPath}/noticeAction!goMyInform.action";
	}
	function showNotice(){
		$('#iframeDialog').dialog('setTitle', '我的公告/公文'); 
		iframeDialog.dialog('open');
		$("#loading").css("display","block");
		document.getElementById("iframe").src = "${pageContext.request.contextPath}/noticeAction!goMyNotice.action";
	}
	function showCdesc(flag,menuItem){
		$.messager.progress({
			text : '数据加载中....',
			interval : 100
		});
		$.ajax({
			url : 'noticeAction!readNotice.action',
			data : {
				noticeId : menuItem.id
			},
			dataType : 'json',
			cache : false,
			success : function(response) {
				$.messager.progress('close');
				if (response && response.context) {
					showCdescDialog.find('div[name=cdesc]').html(response.context);
					showCdescDialog.dialog('open');
				} else {
					$.messager.alert('提示', '没有内容！', 'error');
				}
				// 移除菜单项
				if(flag=="inform"){
					$('#layout_north_informMenu').menu('removeItem', menuItem);
					var text = $('#informMenu')[0].text;
					text = (Number(text.split("条")[0])-1)+"条通知";
					$('#informMenu').menubutton({
				        iconCls: 'icon-tip',
				        menu: '#layout_north_informMenu',
				        text: text
				    });
				}else if(flag=="notice"){
					$('#layout_north_noticeMenu').menu('removeItem', menuItem);
					var text = $('#noticeMenu')[0].text;
					text = (Number(text.split("条")[0])-1)+"条公告/公文";
					$('#noticeMenu').menubutton({
				        iconCls: 'icon-tip',
				        menu: '#layout_north_noticeMenu',
				        text: text
				    });
				}
			}
		});
	}
</script>
<div style="position: absolute; right: 0px; bottom: 0px; ">欢迎&nbsp;<B>${sessionScope.sessionInfo.realName }</B>&nbsp;光临！
	<!--<a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_pfMenu" iconCls="icon-ok">更换皮肤</a> -->
	<a id="informMenu" href="javascript:void(0);" class="easyui-menubutton"></a>
	<a id="noticeMenu" href="javascript:void(0);" class="easyui-menubutton"></a>
	<a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_kzmbMenu" iconCls="icon-help">控制面板</a>
	<a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_zxMenu" iconCls="icon-back">退出</a>
</div>
<div id="layout_north_informMenu" style="width: 160px; display: none;">
</div>
<div id="layout_north_noticeMenu" style="width: 180px; display: none;">
</div>
<div id="iframeDialog" style="display: none;overflow: auto;width: 620px;height: 430px;">
	<div id="loading"  style="position: absolute;z-index: 10000;
         top:30;left:0;width:100%;height:95%;background: #DDDDDB  url('<%=request.getContextPath()%>/css/images/loading.gif') no-repeat center ;text-align:center;">
    </div>
	<iframe name="iframe" id="iframe" src=""  scrolling="no" frameborder="0" style="width:100%;height:100%;">
    </iframe>
</div>
<div id="showCdescDialog" style="display: none;overflow: auto;width: 500px;height: 400px;">
	<div name="cdesc"></div>
</div>


<div id="layout_north_pfMenu" style="width: 120px; display: none;">
	<div onclick="sy.changeTheme('default');">default</div>
	<div onclick="sy.changeTheme('gray');">gray</div>
	<div onclick="sy.changeTheme('cupertino');">cupertino</div>
	<div onclick="sy.changeTheme('dark-hive');">dark-hive</div>
	<div onclick="sy.changeTheme('pepper-grinder');">pepper-grinder</div>
	<div onclick="sy.changeTheme('sunny');">sunny</div>
</div>
<div id="layout_north_kzmbMenu" style="width: 100px; display: none;">
	<div onclick="showUserInfo();">个人信息</div>
	<div class="menu-sep"></div>
	<div>
		<span>更换主题</span>
		<div style="width: 120px;">
			<div onclick="sy.changeTheme('default');">default</div>
			<div onclick="sy.changeTheme('gray');">gray</div>
			<div onclick="sy.changeTheme('cupertino');">cupertino</div>
			<div onclick="sy.changeTheme('dark-hive');">dark-hive</div>
			<div onclick="sy.changeTheme('pepper-grinder');">pepper-grinder</div>
			<div onclick="sy.changeTheme('sunny');">sunny</div>
		</div>
	</div>
</div>
<div id="layout_north_zxMenu" style="width: 100px; display: none;">
	<div onclick="logout(true);">锁定窗口</div>
	<div class="menu-sep"></div>
	<div onclick="logout();">切换用户</div>
	<div onclick="logout(true);">退出系统</div>
</div>

Gspstore/WebRoot/layout/north2.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<script type="text/javascript" charset="utf-8">
	function logout(b) {
		$.post('userAction!logout.action', function() {
			if (b) {
				if (sy.isLessThanIe8()) {
					//loginAndRegDialog.dialog('open');
					window.location.href="login.jsp";
				} else {
					location.replace(sy.bp());
				}
			} else {
				//loginAndRegDialog.dialog('open');
				window.location.href="login.jsp";
			}
		});
	}

	var userInfoWindow;
	function showUserInfo() {
		userInfoWindow = $('<div/>').window({
			modal : true,
			title : '当前用户信息',
			width : 350,
			height : 300,
			collapsible : false,
			minimizable : false,
			maximizable : false,
			href : 'userAction!showUserInfo.action',
			onClose : function() {
				$(this).window('destroy');
			}
		});
	}
	
	var iframeDialog;
	var showCdescDialog;
	$(function() {
		iframeDialog = $('#iframeDialog').show().dialog({
			title : 'POP弹出页面',
			modal : true,
			closed : true,
			maximizable : false,
			onClose : function(){
			    document.getElementById("iframe").src = "about:blank";
			}
		});
		showCdescDialog = $('#showCdescDialog').show().dialog({
			title : '通知内容',
			modal : true,
			closed : true,
			maximizable : true
		});
		// 定时刷新 时间间隔为10分钟
		setInterval("getMyInform()",600000); 
		setInterval("getMyNotice()",600000); 
		getMyInform();
		getMyNotice();
	});
	
	function getMyInform(){
		//取得我的通知信息
		$.ajax({
			url : 'noticeAction!datagridUnGroup.action?queryType=inform&queryUnRead=true',
			dataType : 'json',
			cache : false,
			success : function(response) {
				//if(response.total>0){
				//}
				$('#informMenu').menubutton({
			        iconCls: 'icon-tip',
			        menu: '#layout_north_informMenu',
			        text: response.total+"条通知"
			    });
				$('#layout_north_informMenu').empty();  
				var temp;
				for(var i = 0;i<response.rows.length;i++){
					temp = response.rows[i];
					if(new Date(temp.expiryTime.replace(/-/g,"/"))-new Date()<86400000){
						//24小时后失效
						$('#layout_north_informMenu').menu('appendItem', {
							text: "<font color='red'><strong>"+temp.title+"</strong></font>",
							iconCls: "icon-cancel",
							onclick: function(){
								showCdesc(temp.noticeId);
							}
						});
					}else{
						$('#layout_north_informMenu').menu('appendItem', {
							text: "<strong>"+temp.title+"</strong>",
							onclick: function(){
								showCdesc(temp.noticeId);
							}
						});
					}
				}
				//添加分隔线
				$('#layout_north_informMenu').menu('appendItem', {
					separator: true
				});
				$('#layout_north_informMenu').menu('appendItem', {
					text: '查看全部通知',
					onclick: function(){showInform();}
				});
			}
		});
	}
	
	function getMyNotice(){
		//取得我的通知信息
		$.ajax({
			url : 'noticeAction!datagridUnGroup.action?queryType=notice&queryUnRead=true',
			dataType : 'json',
			cache : false,
			success : function(response) {
				//if(response.total>0){
				//}
				$('#noticeMenu').menubutton({
			        iconCls: 'icon-tip',
			        menu: '#layout_north_noticeMenu',
			        text: response.total+"条公告/公文"
			    });
				$('#layout_north_noticeMenu').empty();  
				var temp;
				for(var i = 0;i<response.rows.length;i++){
					temp = response.rows[i];
					if(new Date(temp.expiryTime.replace(/-/g,"/"))-new Date()<86400000){
						//24小时后失效
						$('#layout_north_noticeMenu').menu('appendItem', {
							text: "<font color='red'><strong>"+temp.title+"</strong></font>",
							iconCls: "icon-cancel",
							onclick: function(){
								showCdesc(temp.noticeId);
							}
						});
					}else{
						$('#layout_north_noticeMenu').menu('appendItem', {
							text: "<strong>"+temp.title+"</strong>",
							onclick: function(){
								showCdesc(temp.noticeId);
							}
						});
					}
				}
				//添加分隔线
				$('#layout_north_noticeMenu').menu('appendItem', {
					separator: true
				});
				$('#layout_north_noticeMenu').menu('appendItem', {
					text: '查看全部公告/公文',
					onclick: function(){showNotice();}
				});
			}
		});
	}
	
	function showInform(){
		$('#iframeDialog').dialog('setTitle', '我的通知'); 
		iframeDialog.dialog('open');
		$("#loading").css("display","block");
		document.getElementById("iframe").src = "${pageContext.request.contextPath}/noticeAction!goMyInform.action";
	}
	function showNotice(){
		$('#iframeDialog').dialog('setTitle', '我的公告/公文'); 
		iframeDialog.dialog('open');
		$("#loading").css("display","block");
		document.getElementById("iframe").src = "${pageContext.request.contextPath}/noticeAction!goMyNotice.action";
	}
	function showCdesc(noticeId){
		$.messager.progress({
			text : '数据加载中....',
			interval : 100
		});
		$.ajax({
			url : 'noticeAction!readNotice.action',
			data : {
				noticeId : noticeId
			},
			dataType : 'json',
			cache : false,
			success : function(response) {
				$.messager.progress('close');
				if (response && response.context) {
					showCdescDialog.find('div[name=cdesc]').html(response.context);
					showCdescDialog.dialog('open');
				} else {
					$.messager.alert('提示', '没有内容！', 'error');
				}
				//TODO刷新一次，否则第二次查看的时候看到的是第一次的内容
				getMyInform();
				getMyNotice();
			}
		});
	}
</script>
<div style="position: absolute; right: 0px; bottom: 0px; ">欢迎&nbsp;<B>${sessionScope.sessionInfo.realName }</B>&nbsp;光临！
	<!--<a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_pfMenu" iconCls="icon-ok">更换皮肤</a> -->
	<a id="informMenu" href="javascript:void(0);" class="easyui-menubutton">通知</a>
	<a id="noticeMenu" href="javascript:void(0);" class="easyui-menubutton">公告/公文</a>
	<a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_kzmbMenu" iconCls="icon-help">控制面板</a>
	<a href="javascript:void(0);" class="easyui-menubutton" menu="#layout_north_zxMenu" iconCls="icon-back">退出</a>
</div>
<div id="layout_north_informMenu" style="width: 160px; display: none;">
</div>
<div id="layout_north_noticeMenu" style="width: 180px; display: none;">
</div>
<div id="iframeDialog" style="display: none;overflow: auto;width: 620px;height: 430px;">
	<div id="loading"  style="position: absolute;z-index: 10000;
         top:30;left:0;width:100%;height:95%;background: #DDDDDB  url('<%=request.getContextPath()%>/css/images/loading.gif') no-repeat center ;text-align:center;">
    </div>
	<iframe name="iframe" id="iframe" src=""  scrolling="no" frameborder="0" style="width:100%;height:100%;">
    </iframe>
</div>
<div id="showCdescDialog" style="display: none;overflow: auto;width: 500px;height: 400px;">
	<div name="cdesc"></div>
</div>


<div id="layout_north_pfMenu" style="width: 120px; display: none;">
	<div onclick="sy.changeTheme('default');">default</div>
	<div onclick="sy.changeTheme('gray');">gray</div>
	<div onclick="sy.changeTheme('cupertino');">cupertino</div>
	<div onclick="sy.changeTheme('dark-hive');">dark-hive</div>
	<div onclick="sy.changeTheme('pepper-grinder');">pepper-grinder</div>
	<div onclick="sy.changeTheme('sunny');">sunny</div>
</div>
<div id="layout_north_kzmbMenu" style="width: 100px; display: none;">
	<div onclick="showUserInfo();">个人信息</div>
	<div class="menu-sep"></div>
	<div>
		<span>更换主题</span>
		<div style="width: 120px;">
			<div onclick="sy.changeTheme('default');">default</div>
			<div onclick="sy.changeTheme('gray');">gray</div>
			<div onclick="sy.changeTheme('cupertino');">cupertino</div>
			<div onclick="sy.changeTheme('dark-hive');">dark-hive</div>
			<div onclick="sy.changeTheme('pepper-grinder');">pepper-grinder</div>
			<div onclick="sy.changeTheme('sunny');">sunny</div>
		</div>
	</div>
</div>
<div id="layout_north_zxMenu" style="width: 100px; display: none;">
	<div onclick="logout(true);">锁定窗口</div>
	<div class="menu-sep"></div>
	<div onclick="logout();">切换用户</div>
	<div onclick="logout(true);">退出系统</div>
</div>

Gspstore/WebRoot/layout/south.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<div style="text-align: center;color: #CC99FF; padding-top: 2px">
  &copy; 版权所有
    <span class="center"><a href="#" title="华英软件">华英软件</a> (推荐使用谷歌浏览器可以获得更快,更安全的页面响应速度) &nbsp;&nbsp; 技术支持:<a href="#" title="">华英软件工作室</a></span>
</div>